var STC = {
    "Florida":       { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [1] },
    "Idaho":         { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [2] },
    "Illinois":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"],  "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "PEF"], "IDFLDS": [3] },
    "Minnesota":     { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"],  "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "PEF"], "IDFLDS": [4] },
    "Wyoming":       { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [5] },
    "Arizona":       { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [6] },
    "Colorado":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [7] },
    "Nevada":        { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [8] },
    "California":    { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [9] },
    "Utah":          { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [10] },
    "New Mexico":    { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [11] },
    "Alabama":       { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [12] },
    "Kansas":        { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [13] },
    "Tennessee":     { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [14] },
    "Virginia":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [15] },
    "Louisiana":     { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [16] },
    "Michigan":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [17] },
    "Mississippi":   { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [18] },
    "Nebraska":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [19] },
    "Indiana":       { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [20] },
    "Maryland":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [21] },
    "Missouri":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [22] },
    "North Carolina":{ "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "PEF"], "IDFLDS": [23] },
    "New Jersey":    { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [24] },
    "New York":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [25] },
    "Oklahoma":      { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [26] },
    "South Carolina":{ "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"],  "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "PEF"], "IDFLDS": [27] },
    "Texas":         { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [28] },	


}