var STC = {
    "Florida": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "PCON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [0] },
    "Idaho": { "IFLDS": ["GWM", "SWM", "AGCON", "UCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [1] },
    "Illinois": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "PCON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [2] },
    "Minnesota": { "IFLDS": ["GWM", "SWM", "ICON", "UCON", "PCON","AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [3] },
    "Wyoming": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [4] },
    "Arizona": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [5] },
    "Colorado": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [6] },
    "Nevada": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [7] },
    "California": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [8] },
    "Utah": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [9] },
    "New Mexico": { "IFLDS": ["GWM", "SWM", "AGCON","UCON","ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND"], "IDFLDS": [10] },
    "Alabama": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF","PEF"], "IDFLDS": [11] },
    "Kansas": { "IFLDS": ["GWM", "SWM","RECM", "AGCON","UCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [12] },
    "Tennessee": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI",  "UEF","PEF"], "IDFLDS": [13] },
    "Virginia": { "IFLDS": ["GWM", "SWM","RECM", "UCON","ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [14] },
    "Louisiana": { "IFLDS": ["GWM", "SWM","RECM", "UCON","ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [15] },
    "Michigan": { "IFLDS": ["GWM", "SWM","RECM", "UCON","ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [16] },
    "Mississippi": { "IFLDS": ["GWM", "SWM","RECM", "UCON","ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [17] },
    "Nebraska": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [18] },
    "Indiana": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [19] }, 
    "Maryland": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF", "AGIND"], "IDFLDS": [20] }, 
    "Missouri": { "IFLDS": ["GWM", "SWM", "RECM", "AGCON", "UCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [21] }, 
    "North Carolina": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [22] }, 
    "New Jersey": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI",  "UEF", "AGIND"], "IDFLDS": [23] }, 
    "New York": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "UEF"], "IDFLDS": [24] }, 
    "Oklahoma": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "AGCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [25] }, 
    "South Carolina": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "ICON", "PCON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "PEF", "UEF"], "IDFLDS": [26] }, 
    "Texas": { "IFLDS": ["GWM", "SWM", "RECM", "UCON", "AGCON", "ICON"], "INDFLDS": ["GWSYA", "ECOR", "SWI", "AGIND", "UEF"], "IDFLDS": [27] } 

}